apiVersion: v1
kind: Service

metadata:
  name: jaeger
  namespace: inventorysystem

spec:
  selector:
    app: jaeger

  type: NodePort

  ports:

  - name: ui
    port: 16686
    targetPort: 16686
    nodePort: 30686

  - name: grpc
    port: 4317
    targetPort: 4317

  - name: http
    port: 4318
    targetPort: 4318