apiVersion: apps/v1
kind: Deployment

metadata:
    name: otel-collector
    namespace: inventorysystem

spec:

    replicas: 1
    selector:
        matchLabels:
            app: otel-collector

    template:

        metadata:
            labels:
                app: otel-collector

        spec:
            containers:
                - name: otel-collector
                  image: otel/opentelemetry-collector-contrib:0.129.1
                  imagePullPolicy: IfNotPresent
                  args:
                    - "--config=/etc/otelcol-contrib/otel-collector-config.yaml"

                  ports:
                    - name: grpc
                      containerPort: 4317
                    
                    - name: http
                      containerPort: 4318
                    
                    - name: health
                      containerPort: 13133

                  livenessProbe:

                    httpGet:
                        path: /
                        port: 13133

                    initialDelaySeconds: 15
                    periodSeconds: 10

                  readinessProbe:

                    httpGet:
                        path: /
                        port: 13133

                    initialDelaySeconds: 5
                    periodSeconds: 5
                  volumeMounts:
                    - name: collector-config
                      mountPath: /etc/otelcol-contrib

            volumes:
                - name: collector-config
                  configMap:
                    name: otel-collector-config
