apiVersion: v1
kind: ConfigMap

metadata:
  name: otel-collector-config
  namespace: inventorysystem

data:
  otel-collector-config.yaml: |
  
    receivers:

      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
          
    exporters:

      otlp:
        endpoint: jaeger:4317
        tls:
          insecure: true

      debug:

    service:

      pipelines:

        traces:
          receivers: [otlp]
          exporters: [debug, otlp]
          
        logs:
          receivers: [otlp]
          exporters: [debug]

        metrics:
          receivers: [otlp]
          exporters: [debug]