apiVersion: apps/v1
kind: Deployment

metadata:
  name: apigateway
  namespace: inventorysystem

spec:
  replicas: 1

  selector:
    matchLabels:
      app: apigateway

  template:
    metadata:
      labels:
        app: apigateway

    spec:
      containers:
      - name: apigateway

        image: localhost:5000/apigateway:1.0
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Docker

        - name: ASPNETCORE_URLS
          value: http://+:8080