apiVersion: apps/v1
kind: Deployment

metadata:
  name: authservice
  namespace: inventorysystem

spec:
  replicas: 1

  selector:
    matchLabels:
      app: authservice

  template:
    metadata:
      labels:
        app: authservice

    spec:
      containers:
      - name: authservice

        image: localhost:5000/authservice:1.0
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Docker

        - name: ASPNETCORE_URLS
          value: http://+:8080

        - name: ConnectionStrings__DefaultConnection
          value: Server=sqlserver;Database=AuthDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;